main = {
    # table 1
    "CDW_SAPP_CUSTOMER" : "SELECT SSN,\
        FIRST_NAME,\
        MIDDLE_NAME,\
        LAST_NAME,\
        CAST(CREDIT_CARD_NO AS INT),\
        CONCAT(STREET_NAME, ', ', APT_NO) AS FULL_STREET_ADDRESS,\
            CUST_CITY,\
        CUST_STATE,\
        CUST_COUNTRY,\
        CUST_ZIP,\
        CONCAT('(123)',\
            SUBSTRING(CUST_PHONE, 0, 3), '-',\
            SUBSTRING(CUST_PHONE, 3, 3))\
        AS CUST_PHONE,\
        CUST_EMAIL,\
        CAST(LAST_UPDATED AS DATE) FROM CDW_SAPP_CUSTOMER",
    # table 2
    "CDW_SAPP_BRANCH" : "SELECT BRANCH_CODE,\
        BRANCH_NAME,\
        BRANCH_STREET,\
        BRANCH_CITY,\
        BRANCH_STATE,\
        BRANCH_ZIP,\
        CONCAT('(',\
            SUBSTRING(BRANCH_PHONE, 0, 3), ')',\
            SUBSTRING(BRANCH_PHONE, 4, 3), '-',\
            SUBSTRING(BRANCH_PHONE, 7))\
        AS BRANCH_PHONE,\
        CAST(LAST_UPDATED AS DATE) FROM CDW_SAPP_BRANCH",
    # table 3
    "CDW_SAPP_CREDIT" : "SELECT CAST(CREDIT_CARD_NO AS INT),\
        CUST_SSN,\
        10000 * Year + 100 * Month + Day AS TIMEID,\
        BRANCH_CODE,\
        TRANSACTION_TYPE,\
        TRANSACTION_VALUE,\
        TRANSACTION_ID FROM CDW_SAPP_CREDIT",
    # table 4
    "CDW_SAPP_PERIOD" : "SELECT DISTINCT Day,\
        Month,\
        Year,\
        10000 * Year + 100 * Month + Day AS TIMEID\
        FROM CDW_SAPP_CREDIT"
}

pk = {
    # table 1
    "CDW_SAPP_CUSTOMER" : "ALTER TABLE CDW_SAPP_CUSTOMER ADD PRIMARY KEY (SSN)",
    # table 2
    "CDW_SAPP_BRANCH" : "ALTER TABLE CDW_SAPP_BRANCH ADD PRIMARY KEY (BRANCH_CODE)",
    # table 3
    "CDW_SAPP_CREDIT" : "ALTER TABLE CDW_SAPP_CREDIT ADD PRIMARY KEY (TRANSACTION_ID)",
    # table 4
    "CDW_SAPP_PERIOD" : "ALTER TABLE CDW_SAPP_PERIOD ADD PRIMARY KEY (TIMEID)"
}

fk = [

    "ALTER TABLE CDW_SAPP_CREDIT ADD FOREIGN KEY (CUST_SSN) REFERENCES CDW_SAPP_CUSTOMER(SSN)",
    "ALTER TABLE CDW_SAPP_CREDIT ADD FOREIGN KEY (TIMEID) REFERENCES CDW_SAPP_PERIOD(TIMEID)",
    "ALTER TABLE CDW_SAPP_CREDIT ADD FOREIGN KEY (BRANCH_CODE) REFERENCES CDW_SAPP_BRANCH(BRANCH_CODE)"
]
     

    
# CHECK DATA TYPES
# TAKE NOTES ON DATA TYPE AND DECISIONS YOU MADE SO FARt