main = {
    # table 1
    "CDW_SAPP_CUSTOMER" : "SELECT SSN,\
        FIRST_NAME,\
        MIDDLE_NAME,\
        LAST_NAME,\
        CAST(CREDIT_CARD_NO AS BIGINT),\
        CONCAT(APT_NO, ',', STREET_NAME) AS FULL_STREET_ADDRESS,\
            CUST_CITY,\
        CUST_STATE,\
        CUST_COUNTRY,\
        CUST_ZIP,\
        CONCAT('(123)',\
            SUBSTRING(CUST_PHONE, 0, 3), '-',\
            SUBSTRING(CUST_PHONE, 4))\
        AS CUST_PHONE,\
        CUST_EMAIL,\
        CAST(LAST_UPDATED AS DATE) FROM CDW_SAPP_CUSTOMER",
    # table 2
    "CDW_SAPP_BRANCH" : "SELECT BRANCH_CODE,\
        BRANCH_NAME,\
        BRANCH_STREET,\
        BRANCH_CITY,\
        BRANCH_STATE,\
        BRANCH_ZIP,\
        CONCAT('(',\
            SUBSTRING(BRANCH_PHONE, 0, 3), ')',\
            SUBSTRING(BRANCH_PHONE, 4, 3), '-',\
            SUBSTRING(BRANCH_PHONE, 7))\
        AS BRANCH_PHONE,\
        CAST(LAST_UPDATED AS DATE) FROM CDW_SAPP_BRANCH",
    # table 3
    "CDW_SAPP_CREDIT" : "SELECT CAST(CREDIT_CARD_NO AS BIGINT),\
        CUST_SSN,\
        10000 * Year + 100 * Month + Day AS TIMEID,\
        BRANCH_CODE,\
        TRANSACTION_TYPE,\
        TRANSACTION_VALUE,\
        TRANSACTION_ID FROM CDW_SAPP_CREDIT",
    # table 4
    "CDW_SAPP_PERIOD" : "SELECT DISTINCT Day,\
        Month,\
        Year,\
        10000 * Year + 100 * Month + Day AS TIMEID\
        FROM CDW_SAPP_CREDIT"
}

pk = {
    # table 1
    "CDW_SAPP_CUSTOMER" : "ALTER TABLE CDW_SAPP_CUSTOMER ADD COLUMN CUST_ID INT AUTO_INCREMENT PRIMARY KEY",
    # table 2
    "CDW_SAPP_BRANCH" : "ALTER TABLE CDW_SAPP_BRANCH ADD PRIMARY KEY (BRANCH_CODE)",
    # table 3
    "CDW_SAPP_CREDIT" : "ALTER TABLE CDW_SAPP_CREDIT ADD PRIMARY KEY (TRANSACTION_ID)",
    # table 4
    "CDW_SAPP_PERIOD" : "ALTER TABLE CDW_SAPP_PERIOD ADD PRIMARY KEY (TIMEID)"
}

fk = [
    "ALTER TABLE CDW_SAPP_CREDIT ADD COLUMN CUST_ID INT",
    "UPDATE CDW_SAPP_CREDIT C JOIN CDW_SAPP_CUSTOMER CU ON C.CUST_SSN = CU.SSN SET C.CUST_ID = CU.CUST_ID",
    "ALTER TABLE CDW_SAPP_CREDIT ADD FOREIGN KEY (CUST_ID) REFERENCES CDW_SAPP_CUSTOMER(CUST_ID)",
    "ALTER TABLE CDW_SAPP_CREDIT ADD FOREIGN KEY (TIMEID) REFERENCES CDW_SAPP_PERIOD(TIMEID)",
    "ALTER TABLE CDW_SAPP_CREDIT ADD FOREIGN KEY (BRANCH_CODE) REFERENCES CDW_SAPP_BRANCH(BRANCH_CODE)",
    "ALTER TABLE CDW_SAPP_CREDIT DROP COLUMN CUST_SSN"
]
     

    
# CHECK DATA TYPES
# TAKE NOTES ON DATA TYPE AND DECISIONS YOU MADE SO FAR